name: DITA compatibility

on:
  pull_request:
    branches:
      - main
    paths:
      - '**.adoc'

jobs:
  content-validation:
    name: Content validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Vale
        run: sudo snap install vale

      - name: Configure Vale
        run: |
          cat <<-'EOF' > dita.ini
          StylesPath = .vale/styles
          MinAlertLevel = warning
          Packages = https://github.com/jhradilek/asciidoctor-dita-vale/releases/latest/download/AsciiDocDITA.zip

          [*.adoc]
          BasedOnStyles = AsciiDocDITA
          EOF

          cat <<-'EOF' > dita.tmpl
          {{range .Files}}
          {{- $path := .Path -}}
          {{- range .Alerts -}}
          {{- $severity := .Severity -}}
          {{$severity}}: {{$path}}: line {{.Line}}: {{.Message}} ({{.Check}})
          {{end -}}
          {{end -}}
          EOF

      - name: Install AsciiDocDITA
        run: vale --config dita.ini sync

      - name: Discover changed files
        id: changed-files
        uses: tj-actions/changed-files@24d32ffd492484c1d75e0c0b894501ddb9d30d62 # v47

      - name: Analyze files
        env:
          CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: echo "$CHANGED_FILES" | xargs -n 4 vale --config dita.ini --output dita.tmpl > VALE_RESULTS || true

      - name: Verify DITA compatibility
        run: |
          ! grep -he '^\(error\|warning\):' VALE_RESULTS
