name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install bats and yamllint
      run: sudo apt install -y bats yamllint

    - name: Install vale
      run: sudo snap install vale

    - name: Ensure all Vale rules are valid YAML files
      run: make validate

    - name: Run tests
      run: make test
